add simple workflow

diff --git a/.github/workflows/simple-workflow.yml b/.github/workflows/simple-workflow.yml
--- a/.github/workflows/simple-workflow.yml
+++ b/.github/workflows/simple-workflow.yml
@@ -1,36 +1,27 @@
-# This is a basic workflow to help you get started with Actions
+name: Funny Action
 
-name: CI
+on: [push]
 
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
+  funny_job:
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Get a random joke from the jokeapi
+        id: joke
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          joke=$(curl -s https://v2.jokeapi.dev/joke/Any?type=single | jq -r '.joke')
+          echo "Joke: $joke"
+          echo "::set-output name=joke::$joke"
+
+      - name: Check if joke contains the word 'cat'
+        run: |
+          if [[ "${{ steps.joke.outputs.joke }}" == *"cat"* ]]; then
+            echo "Found a funny joke about a cat! Proceeding..."
+          else
+            echo "No cat joke found. Failing the action..."
+            exit 1
+        continue-on-error: false
